# Site settings
title: Jan Milosh
email: janmilosh@gmail.com
description: "Full-stack Developer"
baseurl: "/portfolio-jekyll"
url: "https://janmilosh.github.io"
twitter_username: janmilosh
github_username:  janmilosh
paginate: 5

# Build settings
markdown: kramdown
permalink: /:title.html
