# Site settings
title: Jan Milosh
email: janmilosh@gmail.com
description: "Full-stack Developer"
baseurl: ""
url: "http://0.0.0.0:4000"
twitter_username: janmilosh
github_username:  janmilosh
paginate: 5

# Build settings
markdown: kramdown
permalink: /:title.html
